In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
dataset=pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [28]:
dataset=pd.get_dummies(dataset, drop_first=True)
dataset=dataset.astype(int)
dtype=np.int
dataset

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  This is separate from the ipykernel package so we can avoid doing imports until

      age  bmi  children  charges  sex_male  smoker_yes
0      19   27         0    16884         0           1
1      18   33         1     1725         1           0
2      28   33         3     4449         1           0
3      33   22         0    21984         1           0
4      32   28         0     3866         1           0
...   ...  ...       ...      ...       ...         ...
1333   50   30         3    10600         1           0
1334   18   31         0     2205         0           0
1335   18   36         0     1629         0           0
1336   21   25         0     2007         0           0
1337   61   29         0    29141         0           1

[1338 rows x 6 columns]

In [5]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [7]:
independent=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
dependent=dataset[['charges']]

In [15]:
#split into training set and test
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(independent, dependent, test_size = 1/3, random_state = 0)

In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [10]:
!pip install --upgrade numpy

Requirement already satisfied: numpy in c:\users\administrator\appdata\roaming\python\python37\site-packages (1.21.6)

WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -andas (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -cikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -andas (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -cikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ikit-learn (c:\programdata\anaconda3\lib\site-packages)

In [21]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV

#from sklearn.tree import DecisionTreeRegressor
param_grid = {'criterion':['mse','mae'],
            'max_features': ['auto','sqrt','log2'],
            'n_estimators':[10,100]}
grid = GridSearchCV(RandomForestRegressor(), param_grid, refit = True, verbose= 3,n_jobs=-1)
# fitting the model for grid search
grid.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:442: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  fold_sizes = np.full(n_splits, n_samples // n_splits, dtype=np.int)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:102: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  test_mask = np.zeros(_num_samples(X), dtype=np.bool)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:102: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  test_mask = np.zeros(_num_samples(X), dtype=np.bool)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:102: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  test_mask = np.zeros(_num_samples(X), dtype=np.bool)
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 16 concurrent workers.

Fitting 3 folds for each of 12 candidates, totalling 36 fits

[Parallel(n_jobs=-1)]: Done  18 out of  36 | elapsed:    0.9s remaining:    0.9s
[Parallel(n_jobs=-1)]: Done  31 out of  36 | elapsed:    2.2s remaining:    0.3s
[Parallel(n_jobs=-1)]: Done  36 out of  36 | elapsed:    2.6s finished
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:794: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.int)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:715: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.best_estimator_.fit(X, y, **fit_params)

GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=RandomForestRegressor(bootstrap=True, criterion='mse',
                                             max_depth=None,
                                             max_features='auto',
                                             max_leaf_nodes=None,
                                             min_impurity_decrease=0.0,
                                             min_impurity_split=None,
                                             min_samples_leaf=1,
                                             min_samples_split=2,
                                             min_weight_fraction_leaf=0.0,
                                             n_estimators='warn', n_jobs=None,
                                             oob_score=False, random_state=None,
                                             verbose=0, warm_start=False),
             iid='warn', n_jobs=-1,
             param_grid={'criterion': ['mse', 'mae'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

In [22]:
re=grid.cv_results_     #print best parameter after tunning

In [23]:
re

{'mean_fit_time': array([0.11334244, 0.79246306, 0.3248353 , 0.67868416, 0.12869962,
        0.77219208, 0.28351831, 1.65617069, 0.10561419, 1.24020187,
        0.12986263, 1.20404085]),
 'std_fit_time': array([0.03819306, 0.03084745, 0.21989232, 0.07238464, 0.08027606,
        0.06688751, 0.07944961, 0.0295622 , 0.0222449 , 0.05713872,
        0.0132202 , 0.07744234]),
 'mean_score_time': array([0.13092216, 0.04075297, 0.13169845, 0.06114872, 0.39262668,
        0.09733152, 0.07742167, 0.01336694, 0.05716864, 0.0266451 ,
        0.11046378, 0.01992583]),
 'std_score_time': array([0.06628221, 0.0352442 , 0.09787077, 0.0428532 , 0.09379126,
        0.1028094 , 0.06148689, 0.00087348, 0.03207831, 0.00735927,
        0.06717573, 0.00485936]),
 'param_criterion': masked_array(data=['mse', 'mse', 'mse', 'mse', 'mse', 'mse', 'mae', 'mae',
                    'mae', 'mae', 'mae', 'mae'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_max_features': masked_array(data=['auto', 'auto', 'sqrt', 'sqrt', 'log2', 'log2', 'auto',
                    'auto', 'sqrt', 'sqrt', 'log2', 'log2'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_n_estimators': masked_array(data=[10, 100, 10, 100, 10, 100, 10, 100, 10, 100, 10, 100],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'criterion': 'mse', 'max_features': 'auto', 'n_estimators': 10},
  {'criterion': 'mse', 'max_features': 'auto', 'n_estimators': 100},
  {'criterion': 'mse', 'max_features': 'sqrt', 'n_estimators': 10},
  {'criterion': 'mse', 'max_features': 'sqrt', 'n_estimators': 100},
  {'criterion': 'mse', 'max_features': 'log2', 'n_estimators': 10},
  {'criterion': 'mse', 'max_features': 'log2', 'n_estimators': 100},
  {'criterion': 'mae', 'max_features': 'auto', 'n_estimators': 10},
  {'criterion': 'mae', 'max_features': 'auto', 'n_estimators': 100},
  {'criterion': 'mae', 'max_features': 'sqrt', 'n_estimators': 10},
  {'criterion': 'mae', 'max_features': 'sqrt', 'n_estimators': 100},
  {'criterion': 'mae', 'max_features': 'log2', 'n_estimators': 10},
  {'criterion': 'mae', 'max_features': 'log2', 'n_estimators': 100}],
 'split0_test_score': array([0.7653856 , 0.78876488, 0.78339504, 0.80471548, 0.79313242,
        0.8045551 , 0.78721698, 0.8010621 , 0.78688305, 0.80480064,
        0.78718794, 0.80041138]),
 'split1_test_score': array([0.79064692, 0.79547544, 0.77637413, 0.79774877, 0.75922859,
        0.79311082, 0.77735948, 0.7931605 , 0.79971193, 0.81018767,
        0.76580915, 0.79685132]),
 'split2_test_score': array([0.77750264, 0.79335699, 0.75610769, 0.79034923, 0.78041366,
        0.7902278 , 0.78735735, 0.78761035, 0.78897065, 0.79107157,
        0.78398703, 0.79077165]),
 'mean_test_score': array([0.77783109, 0.79252821, 0.77197177, 0.79761247, 0.77760898,
        0.7959742 , 0.78398157, 0.79395229, 0.79184964, 0.80202308,
        0.77900389, 0.79601638]),
 'std_test_score': array([0.01031838, 0.0028022 , 0.01156906, 0.00586742, 0.01398612,
        0.0061906 , 0.00467894, 0.0055216 , 0.00561984, 0.00804403,
        0.00941344, 0.00398045]),
 'rank_test_score': array([10,  6, 12,  2, 11,  4,  8,  5,  7,  1,  9,  3])}

In [29]:
grid_predictions = grid.predict(X_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\base.py:158: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.int)

In [31]:
#print classification report
from sklearn.metrics import r2_score
r_score=r2_score(y_test,grid_predictions)
print("The R_score value for best parameter {}:".format(grid.best_params_),r_score)

The R_score value for best parameter {'criterion': 'mae', 'max_features': 'sqrt', 'n_estimators': 100}: 0.8686811275566595

In [32]:
table=pd.DataFrame.from_dict(re)

In [33]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,mean_test_score,std_test_score,rank_test_score
0,0.113342,0.038193,0.130922,0.066282,mse,auto,10,"{'criterion': 'mse', 'max_features': 'auto', '...",0.765386,0.790647,0.777503,0.777831,0.010318,10
1,0.792463,0.030847,0.040753,0.035244,mse,auto,100,"{'criterion': 'mse', 'max_features': 'auto', '...",0.788765,0.795475,0.793357,0.792528,0.002802,6
2,0.324835,0.219892,0.131698,0.097871,mse,sqrt,10,"{'criterion': 'mse', 'max_features': 'sqrt', '...",0.783395,0.776374,0.756108,0.771972,0.011569,12
3,0.678684,0.072385,0.061149,0.042853,mse,sqrt,100,"{'criterion': 'mse', 'max_features': 'sqrt', '...",0.804715,0.797749,0.790349,0.797612,0.005867,2
4,0.128700,0.080276,0.392627,0.093791,mse,log2,10,"{'criterion': 'mse', 'max_features': 'log2', '...",0.793132,0.759229,0.780414,0.777609,0.013986,11
5,0.772192,0.066888,0.097332,0.102809,mse,log2,100,"{'criterion': 'mse', 'max_features': 'log2', '...",0.804555,0.793111,0.790228,0.795974,0.006191,4
6,0.283518,0.079450,0.077422,0.061487,mae,auto,10,"{'criterion': 'mae', 'max_features': 'auto', '...",0.787217,0.777359,0.787357,0.783982,0.004679,8
7,1.656171,0.029562,0.013367,0.000873,mae,auto,100,"{'criterion': 'mae', 'max_features': 'auto', '...",0.801062,0.793160,0.787610,0.793952,0.005522,5
8,0.105614,0.022245,0.057169,0.032078,mae,sqrt,10,"{'criterion': 'mae', 'max_features': 'sqrt', '...",0.786883,0.799712,0.788971,0.791850,0.005620,7
9,1.240202,0.057139,0.026645,0.007359,mae,sqrt,100,"{'criterion': 'mae', 'max_features': 'sqrt', '...",0.804801,0.810188,0.791072,0.802023,0.008044,1
10,0.129863,0.013220,0.110464,0.067176,mae,log2,10,"{'criterion': 'mae', 'max_features': 'log2', '...",0.787188,0.765809,0.783987,0.779004,0.009413,9
11,1.204041,0.077442,0.019926,0.004859,mae,log2,100,"{'criterion': 'mae', 'max_features': 'log2', '...",0.800411,0.796851,0.790772,0.796016,0.003980,3

In [34]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age:22
BMI:23
Children:0
Sex Male 0 or 1:1
Smoker Yes 0 or 1:0

In [35]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
#␣change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[15520.705]

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\base.py:158: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.int)